### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Mazuruk-O** [krish/microservices-course-on-youtube#6]
Add an annotation `@Repository`

https://github.com/krish/microservices-course-on-youtube/blob/0bc2190f369e5650a530a20d172d8a228a5522ca/video_009-authorization-server-with-mysql/authorization-server/src/main/java/com/krishantha/rentcloud/authorizationserver/repository/UserDetailRepository.java#L8

**Comment by polykhel** [comment]
Hi Mazuruk,

I believe that annotation is not necessary when extending one of the predefined Repository interfaces of Spring like JpaRepository.
